name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        package: [evil, magit, realgud, edts, elpher, which-key-posframe]
    steps:
    - name: Checkout package-build
      uses: actions/checkout@v6
      with:
        path: package-build
        fetch-depth: 1

    - name: Checkout melpa
      uses: actions/checkout@v6
      with:
        path: melpa
        repository: melpa/melpa
        fetch-depth: 1

    - name: Install dependencies
      run: |
        sudo apt-get install emacs git mercurial texinfo imagemagick

    - name: Setup config path
      run: |
        echo "LOAD_PATH = $GITHUB_WORKSPACE/package-build" > melpa/config.mk

    - name: Build ${{ matrix.package }}
      run: |
        cd melpa
        make recipes/${{ matrix.package }}
